# --------------------------------------------------------
# Octree-based Sparse Convolutional Neural Networks
# Copyright (c) 2022 Peng-Shuai Wang <wangps@hotmail.com>
# Licensed under The MIT License [see LICENSE for details]
# Written by Peng-Shuai Wang
# --------------------------------------------------------

SOLVER:
  gpu: 0,
  run: evaluate
  eval_epoch: 1 #5
  eval_step: -1
  logdir: logs/scannet/v300_eval
  ckpt: logs/scannet/v300_train_ckpt/checkpoints/00300.model.pth 
  rand_seed: 123   
DATA:
  test:
    name: scannet

    # octree building
    depth: 10
    full_depth: 2

    # data augmentations
    distort: True
    angle: (0, 0, 180)
    scale: 0.1
    jitter: 0.1
    uniform: True

    location: data/scannet/
    filelist: data/scannet/scannetv2_test_new.txt
    batch_size: 1
    shuffle: False
    # num_workers: 0

MODEL:
  name: unet
  feature: NDF # N -> Normal (3 channels);
               # D -> Displacement (1 channel);
               # F -> Color (3 channels)
  channel: 7
  nout: 201
  nempty: True
  interp: nearest
