SOLVER:
  gpu: 0,
  logdir: logs/scannet/v1000_eval
  run: evaluate
  eval_epoch: 5 #inner voting
  ckpt: logs/scannet/v1000_train_ckpt/checkpoints/01000.model.pth 

DATA:
  test:
    name: scannet

    # octree building
    depth: 9
    node_dis: True
    offset: 0.0

    # data augmentations
    distort: False  # no data augmentation
    angle: (0, 0, 180)
    scale: 0.1
    jitter: 0.1
    uniform: True

    location: data/scannet/test
    filelist: data/scannet/scannetv2_test_new.txt
    batch_size: 1
    shuffle: False
    in_memory: False
    # num_workers: 0

MODEL:
  name: unet
  channel: 7
  nout: 201
  depth: 9
  nempty: True
  interp: nearest
