SOLVER:
  gpu: 0,3
  run: train
  logdir: logs/scannet/D10_2cm_simsiam
  max_epoch: 600
  test_every_epoch: 5
  log_per_iter: 20
  weight_decay: 0.001
  amp: native
  precision: 16
  # learning rate
  lr: 0.05 # 0.05
  lr_type: poly
  milestones: (360,480)  # has no effect for `poly`

DATA:
  train:
    name: scannet

    # octree building
    depth: 10
    full_depth: 2

    # data augmentations
    distort: True
    angle: (0, 0, 180)
    scale: 0.2
    jitter: 0.1
    uniform: True

    # data loading
    location: scannet/
    filelist: scannet/train.txt
    batch_size: 1
    shuffle: True
    num_workers: 10

  test:
    name: scannet

    # octree building
    depth: 10
    full_depth: 2

    # data augmentations
    distort: True  # no data augmentation
    angle: (0, 0, 180)
    scale: 0.1
    jitter: 0.1
    uniform: True

    # data loading
    location: scannet
    filelist: scannet/val.txt
    batch_size: 1
    shuffle: False
    num_workers: 10

MODEL:
  name: unet
  label_embedding_path: label_text/explaination_embeddings.pth
  label_embedding_type: weight3d
  
  # N -> Normal (3 channels);
  # D -> Displacement (1 channel);
  # F -> Color (3 channels)
  # P -> Position (3 channels)
  feature: NDF
  channel: 7
  nout: 201
  nempty: True
  interp: nearest
  sync_bn: True

LOSS:
  mask: 0
  num_class: 201
  accumulation: 1