# --------------------------------------------------------
# Octree-based Sparse Convolutional Neural Networks
# Copyright (c) 2022 Peng-Shuai Wang <wangps@hotmail.com>
# Licensed under The MIT License [see LICENSE for details]
# Written by Peng-Shuai Wang
# --------------------------------------------------------

SOLVER:
  gpu: 0,
  run: train
  logdir: logs/kitti/D12_5cm
  max_epoch: 20
  test_every_epoch: 1
  log_per_iter: 50
  weight_decay: 0.0001

  # learning rate
  lr: 0.06
  lr_type: poly
  milestones: (10,14,18)  # has no effect for `poly`


DATA:
  train:
    name: kitti

    # octree building
    depth: 12
    full_depth: 2

    # data augmentations
    distort: True
    angle: (0, 0, 180)
    scale: 0.05
    jitter: 0.0
    uniform: True

    # data loading
    location: data/SemanticKITTI
    filelist: data/SemanticKITTI/train.txt
    batch_size: 2
    shuffle: True
    # num_workers: 0

  test:
    name: kitti

    # octree building
    depth: 12
    full_depth: 2

    # data augmentations
    distort: False  # no data augmentation
    angle: (0, 0, 180)
    scale: 0.05
    jitter: 0.0
    uniform: True

    # data loading
    location: data/SemanticKITTI
    filelist: data/SemanticKITTI/val.txt
    batch_size: 1
    shuffle: False
    # num_workers: 0

MODEL:
  name: unet
  feature: PF  # P -> Position (3 channels);
               # F -> Lidar Density (1 channel)
  channel: 4
  nout: 20
  nempty: True
  interp: nearest
  sync_bn: False

LOSS:
  mask: 0
  num_class: 20
