# --------------------------------------------------------
# Octree-based Sparse Convolutional Neural Networks
# Copyright (c) 2022 Peng-Shuai Wang <wangps@hotmail.com>
# Licensed under The MIT License [see LICENSE for details]
# Written by Peng-Shuai Wang
# --------------------------------------------------------

version: 2

build:
  image: latest

python:
  version: "3.7"
  install:
    - requirements: docs/requirements.txt
    # - method: pip
    - method: setuptools
      path: .

formats: []
